app/__init__.py
from flask import Flask
import os

from .auth import auth
from .setting import setting
from app.db import init_db_command

def create_app():
    app = Flask(__name__)
    app.config.from_mapping(
        SECRET_KEY=os.environ.get('FLASK_SECRET_KEY'),
        DATABASE_HOST=  os.environ.get('FLASK_DATABASE_HOST'),
        DATABASE_PASSWORD=  os.environ.get('FLASK_DATABASE_PASSWORD'),
        DATABASE_USER=  os.environ.get('FLASK_DATABASE_USER'),
        DATABASE=   os.environ.get('FLASK_DATABASE'),
        MAIL_SERVER = os.environ.get('FLASK_MAIL_SERVER'),
        MAIL_PORT = os.environ.get('FLASK_MAIL_PORT'),
        MAIL_USE_SSL = os.environ.get('FLASK_MAIL_USE_SSL'),
        MAIL_USE_TSL = os.environ.get('FLASK_MAIL_USE_TSL'),
        MAIL_USERNAME = os.environ.get('FLASK_MAIL_USERNAME'),
        MAIL_PASSWORD = os.environ.get('FLASK_MAIL_PASSWORD')
    )
    
    app.cli.add_command(init_db_command)
    
    app.register_blueprint(auth)
    app.register_blueprint(setting)
        
    return app

app/personal_informacion/__init__.py
from . import full_name, profesiones, descripcion, services, social_media, portfolio, subir_a_profolio as s
def details_portfolio():
    json = dict()
    json['name'] = full_name.data()
    json['profesiones'] = profesiones.data()
    json['social_media'] = social_media.data()
    json['descriptions'] = descripcion.data()
    json['courses'] = services.data()
    json['type_works'] = portfolio.type_works()
    json['works'] = portfolio.data()
    
    return json

app/setting/__init__.py
from flask import Blueprint

setting = Blueprint('setting', __name__, url_prefix ='/setting')

from . import routes

app/setting/routes.py
from . import setting
from flask import render_template, url_for, redirect, request, flash
from . import route_images, route_profesion, route_description, route_curse, route_proyecto, route_icon, route_social, route_personal_informacion
from app.auth.routes import login_required
@setting.route('/')
@login_required
def index():
    flash('cualquier ajuste se reflajera directamente en la pagina principal')
    return render_template('setting/index.html')

@setting.route('/icon', methods = ['GET', 'POST'])
@login_required
def icon():
    if request.method == 'POST':
        route_icon.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_icon.html')

@setting.route('/personal', methods = ['GET', 'POST'])
@login_required
def personal():
    if request.method == 'POST':
        route_personal_informacion.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_personal_informacion.html')

@setting.route('/description', methods = ['GET', 'POST'])
@login_required
def description():
    if request.method == 'POST':
        route_description.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_description_perfil.html')

@setting.route('/images', methods = ['GET', 'POST'])
@login_required
def images():
    if request.method == 'POST':
        route_images.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_image.html')

@setting.route('/profesion', methods = ['GET', 'POST'])
@login_required
def profesion():
    if request.method == 'POST':
        route_profesion.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_profesion.html')

@setting.route('/social', methods = ['GET', 'POST'])
@login_required
def social():
    if request.method == 'POST':
        route_social.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_social_media.html')

@setting.route('/curse', methods = ['GET', 'POST'])
@login_required
def curse():
    if request.method == 'POST':
        route_curse.function()
        return redirect(url_for('setting.index'))
    return render_template('setting/form_course.html')

@setting.route('/proyecto', methods = ['GET', 'POST'])
@login_required
def Proyecto():
    if request.method == 'POST':
        error = route_proyecto.function()
        if error is None:
            return redirect(url_for('setting.index'))
        flash(error)
        return redirect(url_for('setting.index'))
    return render_template('setting/form_works.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
<!-- For resposive -->
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>{% block title %}Joel Flores|{% endblock %}</title>
    <meta content="Portafolio personal" name="description" />
<!-- Icon -->
    <link rel="icon" type="images/png" href="{{url_for('static', filename='images/icon/code.png')}}" />
<!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i|Playfair+Display:400,400i,500,500i,600,600i,700,700i,900,900i" rel="stylesheet"/>
<!-- CSS Files -->
    <link href="{{url_for('static', filename='framework/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename='framework/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet"/>
    <link href="{{url_for('static', filename='framework/boxicons/css/boxicons.min.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename='framework/glightbox/css/glightbox.min.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename='framework/swiper/swiper-bundle.min.css')}}" rel="stylesheet" />
<!-- CSS Manjor -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" />
</head>
<body>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-light alert-dismissible fade show" role="alert">
    <p class="h4 text-dark text-center">{{message.capitalize()}}</p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

{% import 'macros.html' as macros %}

{%block main%} {%endblock%}

<!-- ======= Footer ======= -->
{% include 'footer.html'%}

    <a
        href="#"
        class="back-to-top d-flex align-items-center justify-content-center"
        ><i class="bi bi-arrow-up-short"></i
    ></a>
<!-- JS Files -->
    <script src="{{url_for('static', filename='framework/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='framework/glightbox/js/glightbox.min.js')}}"></script>
    <script src="{{url_for('static', filename='framework/isotope-layout/isotope.pkgd.min.js')}}"></script>
    <script src="{{url_for('static', filename='framework/swiper/swiper-bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='framework/typed.js/typed.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/validate.js')}}"></script>

<!-- JS Manjor -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

app/templates/blog/blog.html
<div id="blog" class="col-md-12">
    <div class="block-main mb-30">
        <img src="{{url_for('static', filename='assets/img/blog-post-big.jpg')}}" class="img-fluid center" alt="reviews2">
        <div class="content-main single-post padDiv">
            <div class="journal-txt">
            <h4><a href="#">SO LETS MAKE THE MOST IS BEAUTIFUL</a></h4>
            </div>
            <div class="post-meta">
            <ul class="list-unstyled mb-0">
                <li class="author">by:<a href="#">medsign</a></li>
                <li class="date">date:<a href="#">March 31, 2017</a></li>
                <li class="commont"><i class="ion-ios-heart-outline"></i><a href="#">3 Comments</a></li>
            </ul>
            </div>
            <p class="mb-30">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to
            using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web
            sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
            <p class="mb-30">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type
            specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            <blockquote>If you are still looking for that one person who will change your life, take a look in the mirror.</blockquote>
            <p class="mb-30">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in
            Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections
            1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum,
            "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
        </div>
    </div>
</div>

app/templates/blog/coments.html
<div id="coments" class="col-md-12">
    <div class="comments text-left padDiv mb-30">
        <div class="entry-comments">
            <h6 class="mb-30">4 comments</h6>
            <ul class="entry-comments-list list-unstyled">
                <li>
                    <div class="entry-comments-item">
                        <img src="assets/img/avatar.jpg" class="entry-comments-avatar" alt="">
                        <div class="entry-comments-body">
                            <span class="entry-comments-author">Sommer Christian</span>
                            <span><a href="#">fev 14, 2018 at 12:48 pm</a></span>
                            <p class="mb-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam justo, ullamcorper tincidunt pellentesque in, condimentum ut enim. Aenean at pharetra diam, quis vulputate urna. </p>
                            <a class="rep" href="#">Reply</a>
                        </div>
                    </div>
                    <ul class="entry-comments-reply list-unstyled">
                        <li>
                            <div class="entry-comments-item">
                                <img src="assets/img/avatar.jpg" class="entry-comments-avatar" alt="">
                                <div class="entry-comments-body">
                                    <span class="entry-comments-author">Sara Smith</span>
                                    <span><a href="#">fev 14, 2018 at 12:51 pm</a></span>
                                    <p class="mb-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam justo, ullamcorper tincidunt pellentesque in, condimentum ut enim. Aenean at pharetra diam, quis vulputate urna.</p>
                                    <a class="rep" href="#">Reply</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li>
                    <div class="entry-comments-item">
                        <img src="assets/img/avatar.jpg" class="entry-comments-avatar" alt="">
                        <div class="entry-comments-body">
                            <span class="entry-comments-author">Andrew Lupkin</span>
                            <span><a href="#">fev 14, 2018 at 12:55 pm</a></span>
                            <p class="mb-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam justo, ullamcorper tincidunt pellentesque in, condimentum ut enim. Aenean at pharetra diam, quis vulputate urna. </p>
                            <a class="rep" href="#">Reply</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

app/templates/blog/header.html
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">
        <a href="/" class="logo">
            <img src="{{url_for('static', filename='images/joelicon.png')}}" alt="" class="img-fluid"/>
        </a>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="/">Home</a></li>
                <li><a class="nav-link scrollto" href="#coments">Coments</a></li>
                <li><a class="nav-link scrollto" href="#blog">Blog</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
    </div>
</header>

app/templates/blog/index.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}{{super()}}Blog{% endblock %}
{%block main%}
<!-- ======= Header ======= -->
{% include 'blog/header.html' %}
<main>
    <div class="main-content paddsection">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-md-offset-2">
                    <div class="row">
                        <div class="container-main single-main">
                            <!-- ======= Blog ======= -->
                            {% include 'blog/blog.html' %}
                            <!-- ======= Coments ======= -->
                            {% include 'blog/coments.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{%endblock%}

app/templates/footer.html
<footer id="footer" class="text-center text-bg p-3">
    <div class="container">
        <article class="socials-media text-center">
            <ul class="list-unstyled">
                {{macros.render_list_social_media(json.social_media)}}
            </ul>
        </article>
        <p> <a href="/auth/login">&#169:2022 Copyright</a>  </p>
        <article class="credits">
            Inspiraciones
            <a href="https://www.youtube.com/c/Platzi">Platzi</a>
            <a href="https://www.youtube.com/c/HolaMundoDev">Hola_Mundo</a>
            <a href="https://www.youtube.com/c/soydalto">Soy_Dalto</a>
        </article>
    </div>
</footer>

app/templates/macros.html
{% macro render_name(full_name) %}
{{full_name.nombre.capitalize()}} {{full_name.apellido.capitalize()}}
{% endmacro%}

{% macro render_list_profesion(profesiones) %}
    {% for profesion in profesiones %}
                {{profesion.profesion}},
    {% endfor %}
{% endmacro %}

{% macro render_list_profesions(profesiones) %}
            <p>    
            {% for profesion in profesiones %}
                {{profesion.profesion}}
            {% endfor %}
            </p>
{% endmacro %}

{% macro render_list_social_media(social_media) %}
    {% for perfil in social_media %}
                <li>
                    <a href="{{perfil.link}}" target="_blank"><i class="bi bi-{{perfil.name}}"></i></a>
                </li>
    {% endfor %}
{% endmacro %}

{% macro render_description(description) %}
                <p class="p-heading">{{description.titulo}}</p>
                <p class="separator"><br>{{description.descripcion}}</p>
                <p class="separator">{{description.opcional_descripcion}}</p>
{% endmacro %}

{% macro render_list_courses(courses) %}
    {% for course in courses %}
                <!-- courses item -->
                <article class="swiper-slide">
                    <div class="services-block">
                    <span>
                        <a href="{{course.url}}" target="_blank"><img src="{{url_for ('static', filename = course.icono_ruta)}}" alt=""></a>
                    </span>
                    <p>{{course.nombre.capitalize()}}</p>
                    </div>
                </article>
    {% endfor %}
{% endmacro %}

{% macro render_list__menu_works(works) %}
    {% for work in works %}
                <li data-filter=".filter-{{work.tipo}}">{{work.tipo}}</li>
    {% endfor %}
{% endmacro %}

{% macro render_list_works(works) %}
    {% for work in works %}
            <article class="col-lg-4 col-md-6 portfolio-item filter-{{work.tipo}}">
                <img src="{{url_for ('static', filename = work.archivos.0)}}" class="img-fluid" alt=""/>
                <div class="portfolio-info">
                    <h4>{{work.titulo}}</h4>
                    <p>{{work.descripcion}}</p>
                    <a href="{{url_for ('static', filename = work.archivos.1)}}" data-gallery="portfolioGallery" class="portfolio-lightbox preview-link" title="{{work.titulo}}"><i class="bx bx-plus"></i></a>
                    <a href="{{work.url_proyecto}}" target="_blank" class="details-link" title="More Details" ><i class="bx bx-link"></i ></a>
                </div>
            </article>
    {% endfor %}
{% endmacro %}

{% macro render_list_journal(journals) %}
    {% for journal in journals %}
                <article class="col-lg-4 col-md-6">
                    <div class="journal-info">
                        <a href="/blog"><img src="./static/{{journal.image}}" class="img-responsive" alt="img"/></a>
                        <div class="journal-txt">
                            <h4 class="h4">
                            <a href="/blog">{{journal.title}}</a>
                            </h4>
                            <p class="separator">{{journal.concept}}</p>
                        </div>
                    </div>
                </article>
    {% endfor %}
{% endmacro %}

app/templates/principal/about.html
<section id="about" class="paddsection">
    <div class="container">
        <div class="row justify-content-between">
            <article class="col-lg-4">
                <div class="div-img-bg">
                    <div class="about-img">
                        <img src="{{url_for('static', filename='images/perfil/principal.jpg')}}" class="img-responsive" alt="me"/>
                    </div>
                </div>
            </article>
            <article class="col-lg-7">
            <div class="about-descr">
                {{macros.render_description(json.descriptions)}}
            </div>
            </article>
        </div>
    </div>
</section>

app/templates/principal/contact.html
<section id="contact" class="paddsection">
    <div class="container">
        <div class="contact-block1">
            <div class="row">
                <article class="col-lg-6">
                    <div class="contact-contact">
                    <h2 class="mb-30">LET'S WORK TOGETHER</h2>
                    <!--habilitar al tener dominio
                    <ul class="contact-details">
                        <li><span>El Alto</span></li>
                        <li><span>La Paz, Bolivia</span></li>
                        <li><span></span></li>
                        <li><span>joel@jf.com</span></li> habilitar al tener dominio
                    </ul>-->
                    </div>
                </article>

                <article class="col-lg-6">
                    <form action="/email" method="POST" class="email-form">
                        <div class="row gy-3">
                            <div class="col-lg-6">
                                <section class="form-group">
                                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required/>
                                </section>
                            </div>

                            <div class="col-lg-6">
                                <section class="form-group">
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required/>
                                </section>
                            </div>

                            <div class="col-lg-12">
                                <section class="form-group">
                                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required/>
                                </section>
                            </div>

                            <div class="col-lg-12">
                                <section class="form-group">
                                    <textarea class="form-control" name="message" placeholder="Message" required></textarea>
                                </section>
                            </div>
                            <div class="mt-0">
                                <input type="submit" class="btn btn-defeault btn-send" value="Sendmessage">
                            </div>
                        </div>
                    </form>
                </article>
            </div>
        </div>
    </div>
</section>

app/templates/principal/header.html
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">
        <a href="/" class="logo">
            <img src="{{url_for('static', filename='images/icon_navbar/code.png')}}" alt="" class="img-fluid"/>
        </a>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                <li><a class="nav-link scrollto" href="#about">About</a></li>
                <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>
                <li><a class="nav-link scrollto" href="#journal">Blog</a></li>
                <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
    </div>
</header>

app/templates/principal/hero.html
<section id="hero" class="home">
    <div class="container">
        <div class="hero-content">
            <h1>Soy
                <span class="typed" data-typed-items="{{macros.render_name(json.name)}},{{macros.render_list_profesion(json.profesiones)}}"></span>
            </h1>
            {{macros.render_list_profesions(json.profesiones)}}
            <ul class="list-unstyled list-social">
                {{macros.render_list_social_media(json.social_media)}}
            </ul>
        </div>
    </div>
</section>

app/templates/principal/index.html
{% extends "base.html" %}
{% block title %}{{super()}}Portfolio{% endblock %}
{%block main%}
<!-- ======= Header ======= -->
{% include 'principal/header.html' %}
<main>
<!-- ======= Hero ======= -->
{% include 'principal/hero.html' %}
<!-- ======= About ======= -->
{% include 'principal/about.html' %}
<!-- ======= Services ======= -->
{% include 'principal/services.html' %}
<!-- ======= Portfolio ======= -->
{% include 'principal/portfolio.html' %}
<!-- ======= Contact Section ======= -->
{% include 'principal/contact.html' %}
</main>
{%endblock%}

app/templates/principal/journal.html
<section id="journal" class="text-left paddsection">
    <section class="container">
        <h2 class="section-title text-center">Extras</h2>
    </section>
    <section class="container">
        <div class="journal-block">
            <div class="row">
                {{macros.render_list_journal(json.journals) }}
            </div>
        </div>
    </section>
</section>

app/templates/principal/portfolio.html
<section id="portfolio" class="paddsection">
    <article class="container">
        <h2 class="section-title text-center">Mi Portafolio</h2>
    </article>
    <section class="container">
        <section class="row">
            <article class="col-lg-12 d-flex justify-content-center">
            <ul id="portfolio-flters">
                <li data-filter="*" class="filter-active">All</li>
                {{macros.render_list__menu_works(json.type_works)}}
            </ul>
            </article>
        </section>
        <section class="row portfolio-container">
            {{macros.render_list_works(json.works)}}
        </section>
    </section>
</section>

app/templates/principal/services.html
<section id="services">
    <div class="container">
        <article class="container">
            <h2 class="section-title text-center">Mis Skills</h2>
        </article>
        <div class="services-slider swiper" data-aos="fade-up" data-aos-delay="100">
            <div class="swiper-wrapper">
                {{macros.render_list_courses(json.courses)}}
            <!-- End courses item -->
            </div>
            <div class="swiper-pagination"></div>
        </div>
    </div>
</section>

app/templates/setting/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
<!-- For resposive -->
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>{% block title %}Configuracion{% endblock %}</title>
    <meta content="Portafolio personal" name="description" />
<!-- Icon -->
    <link rel="icon" type="images/png" href="{{url_for('static', filename='images/icon/icon.png')}}" />
<!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i|Playfair+Display:400,400i,500,500i,600,600i,700,700i,900,900i" rel="stylesheet"/>
<!-- CSS Files -->
    <link href="{{url_for('static', filename= 'framework/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename = 'css/setting.css')}}" rel="stylesheet" >
</head>
<body>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-light alert-dismissible fade show" role="alert">
        <strong class="text-dark">{{message.upper()}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}
{% endwith %}


{%block main%} {%endblock%}


<!-- JS Files -->
    <script src="{{url_for('static', filename='framework/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
</body>
</html>

app/templates/setting/form_course.html
{% extends "setting/index.html" %}
{% block title %}{{super()}}{% endblock %}
{%block div%}
<section class="card m-2 bg-dark text-white border border-light">
  <article class="card-body">
      <h4 class="card-title text-center">{{'Agregar nuevo Curso'.upper()}}</h4>
      <form action="/setting/curse" class="form-floating text-dark"  method="POST" enctype="multipart/form-data">
  
        <div class="form-floating mb-3  m-2">
          <input type="text" class="form-control" name="titulo" required>
          <label class="text-dark" for="floatingInput">{{'Titulo del curso'.upper()}}</label>
        </div>
      
        <div class="form-floating m-2">
          <input type="text" class="form-control" name="url" required>
          <label class="text-dark" for="floatingInput">{{'Enlace del Curso'.upper()}}</label>
        </div>
        
        <div class="mb-3 m-2">
          <label class="text-dark" class="form-label text-white">{{'Select an SVG file:'.upper()}}</label>
          <input type="file" class="form-control" id="svgFile" name="svgFile" accept="image/svg+xml" required>
        </div>
        
        <button type="submit" class="btn btn-secondary m-2">{{'Enviar'.upper()}}</button>
      
      </form>
  </article>
</section>
{%endblock%}

app/templates/setting/index.html
{% extends "setting/base.html" %}
{% block title %}{{super()}}{% endblock %}
{%block main%}
<main class="p-3 mb-2">
  <div>
    {%block div%}
    <button class="btn btn-secondary m-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
      DESEAS EDITAR
    </button>
    {%endblock%}
  </div>
      
  <div class="offcanvas offcanvas-start m-2 bg-secondary text-white border border-light" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasExampleLabel">{{'Configuracion'.upper()}}</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div>
        {{'Modifica partes del Perfil o agrega nuevos proyectos, redes sociales o cursos'.upper()}}
      </div>
      <div class="mt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.icon')}}">{{'Cambiar Icono de la web'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.personal')}}">{{'Informacion Personal'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.description')}}">{{'Descripcion Personal'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.images')}}">{{'Imagenes de Portada y Perfil'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.profesion')}}">{{'Agregar Profesion'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.social')}}">{{'Agregar Redes Sociales'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.curse')}}">{{'Agregar Nuevos Cursos'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('setting.Proyecto')}}">{{'Agregar Proyectos Realizados'.capitalize()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.register')}}">{{'Registar usuario'.upper()}}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
<section class="notFound">
  <div class="img">
    <img src="https://assets.codepen.io/5647096/backToTheHomepage.png" alt="Back to the Homepage"/>
    <img src="https://assets.codepen.io/5647096/Delorean.png" alt="El Delorean, El Doc y Marti McFly"/>
  </div>
        
  <div class="texts">
    <h1>AJUSTES</h1>
    <h2>DEL SISTEMA</h2>
    <h3>BACK TO HOME?</h3>
    <a href="{{url_for('auth.logout')}}" class="yes">YES</a>
  </div>
</section>

</main>
{%endblock%}